### ISSUE TITLE
Сохранять изменившийся порядок книг только если есть изменения

### ISSUE THREAD

**Issue by bsavelev** [amigo/biblio#1]
Представим, что есть полка, на ней есть 1000 книг. Меняя местами 1 и 2 книги, сколько раз будет вызвано save()?

**Comment by amigo** [comment]
1000 раз.

**Comment by bsavelev** [comment]
логично предположить, что должно 2 раза

**Comment by amigo** [comment]
Судя по представленному коду, метод save() будет вызван столько раз, сколько указано в списке книг данной категории.
