### ISSUE TITLE
Возможна ли ситуация, когда 2 книги имеют одинаковый индекс места на полке?

### ISSUE THREAD

**Issue by bsavelev** [amigo/biblio#2]

**Comment by amigo** [comment]
Да, по умолчанию все книги имеют index равный нулю.

**Comment by bsavelev** [comment]
Ок, возможно ли такое во время или после перестановки с использованием book_sorting()?

**Comment by amigo** [comment]
Конечно возможно.

**Comment by bsavelev** [comment]
это же плохо! получается полка, где на одном месте стоят 2 книги одновременно. это оторвано от реальности)

**Comment by amigo** [comment]
Такова цифровая реальность. Увы.

**Comment by bsavelev** [comment]
это можно решить, если обернуть все сохранения в транзакцию

**Comment by amigo** [comment]
Зачем оборачивать в транзакцию, у нас же index не уникальный?

**Comment by bsavelev** [comment]
ну так а почему он не уникальный?) на одной полке каждому индексу может соотв. лишь одна книга

**Comment by amigo** [comment]
Потому что в задаче об уникальности индекса ничего сказано не было.
